# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18151f44570c8d2930ae02bfabaa4f8cadec4cc05623e96cefb1cedfeb002c76fc3d1d53efa16b55fb4b943b20da6493c4deb625b4da8aa48f3883f143277613

test:
  secret_key_base: 0ba8958b35f9f968ab60f76a802ce98e012f7b6c252557525036b10a30118337565703dfbae694ed42bbdf2de5fdf78d408fd8ffd31ce78300a57f87d459f78d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
