class CreateBicycles < ActiveRecord::Migration[5.0]
  def change
    create_table :bicycles do |t|
      t.integer :price
      t.references :brand, foreign_key: true
      t.string :c1
      t.string :c2
      t.string :c3
      t.string :c4
      t.string :c5
      t.integer :c6
      t.string :c7
      t.boolean :c8
      t.boolean :c9
      t.boolean :c10
      t.integer :c11
      t.integer :c12
      t.integer :c13
      t.string :c14
      t.decimal :c15
      t.decimal :c16
      t.string :c17
      t.string :c18
      t.boolean :c19
      t.string :c20
      t.integer :c21
      t.boolean :c22
      t.boolean :c23
      t.boolean :c24
      t.boolean :c25
      t.boolean :c26
      t.integer :c27
      t.boolean :c28
      t.boolean :c29
      t.boolean :c30
      t.boolean :c31
      t.boolean :c32
      t.string :c33
      t.string :c34
      t.boolean :c35
      t.boolean :c36
      t.boolean :c37
      t.boolean :c38
      t.integer :c39
      t.integer :c40
      t.string :c41
      t.string :c42
      t.string :c43
      t.string :c44
      t.string :c45
      t.string :c46
      t.string :c47
      t.string :c48
      t.integer :c49
      t.integer :c50
      t.boolean :c51
      t.integer :c52
      t.integer :c53
      t.integer :c54
      t.string :c55
      t.string :c56
      t.string :c57
      t.string :c58
      t.string :c59
      t.string :c60
      t.boolean :c61
      t.boolean :c62
      t.boolean :c63
      t.string :c64
      t.string :c65
      t.string :c66
      t.boolean :c67
      t.boolean :c68
      t.string :c69
      t.string :c70
      t.string :c71
      t.boolean :c72
      t.boolean :c73
      t.boolean :c74
      t.boolean :c75
      t.boolean :c76
      t.boolean :c77
      t.boolean :c78
      t.integer :c79
      t.string :c80
      t.decimal :c81
      t.decimal :c82
      t.decimal :c83
      t.boolean :c84
      t.boolean :c85

      t.timestamps
    end
  end
end
