class CreateBicycles < ActiveRecord::Migration[5.0]
  def change
    create_table :bicycles do |t|
      t.integer :price
      t.references :brand, foreign_key: true
      t.string :c1
      t.string :c2
      t.string :c3
      t.string :c4
      t.string :c5
      t.string :c6
      t.string :c7
      t.string :c8
      t.string :c9
      t.string :c10
      t.string :c11
      t.string :c12
      t.string :c13
      t.string :c14
      t.string :c15
      t.string :c16
      t.string :c17
      t.string :c18
      t.string :c19
      t.string :c20
      t.string :c21
      t.string :c22
      t.string :c23
      t.string :c24
      t.string :c25
      t.string :c26
      t.string :c27
      t.string :c28
      t.string :c29
      t.string :c30
      t.string :c31
      t.string :c32
      t.string :c33
      t.string :c34
      t.string :c35
      t.string :c36
      t.string :c37
      t.string :c38
      t.string :c39
      t.string :c40
      t.string :c41
      t.string :c42
      t.string :c43
      t.string :c44
      t.string :c45
      t.string :c46
      t.string :c47
      t.string :c48
      t.string :c49
      t.string :c50
      t.string :c51
      t.string :c52
      t.string :c53
      t.string :c54
      t.string :c55
      t.string :c56
      t.string :c57
      t.string :c58
      t.string :c59
      t.string :c60
      t.string :c1
      t.string :c2
      t.string :c3
      t.string :c4
      t.string :c5
      t.string :c6
      t.string :c7
      t.string :c8
      t.string :c9
      t.string :c10
      t.string :c1
      t.string :c2
      t.string :c3
      t.string :c4
      t.string :c5
      t.string :c6
      t.string :c7
      t.string :c8
      t.string :c9
      t.string :c10
      t.string :c1
      t.string :c1
      t.string :c1
      t.string :c1

      t.timestamps
    end
  end
end
